# Engine
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

encoding: utf-8

permalink: pretty

url: https://www.fxhu.tk
paginate: 5

# If not set custom url: if user pages, then use "/"; if project page, use "/project-name" (without trailing slash).
baseurl: /

# Site info
title: ZNHOO
tagline: 'Whatever you are, be a good one!'
description: 'Make yourself at home. Contact me at <a href="mailto:{{ site.author.email }}">Email</a>.'

# About/contact
author:
  name: ZNHOO
  email: youwu@inventati.org

# Custom vars
version: 1.0.0
