# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ZNHOO
tagline:             'Whatever you are, be a good one!'
description:         'I am ZNHOO. Make yourself at home. Contact me at twitter <a href="https://twitter.com/znhoo" target="_blank">@znhoo</a>.'
  # if use custom domain, use / for baseurl. But if don't use custom domain, replace / with "http://outsinre.github.com/" or "http://outsinre.github.io/"
baseurl:             /
paginate:            5

# About/contact
author:
  name:              ZNHOO
  url:               https://twitter.com/znhoo
  email:             bob@noreply.com

# Custom vars

version:             1.0.0

# removed configuration
# url	  http://fangxiang.tk
# github:
#   repo:  https://github.com/outsinre/outsinre.github.com
