# Engine
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
#  syntax_highlighter: rouge
highlighter: rouge

# encoding of filenames
encoding: utf-8

# Permalinks
permalink: pretty

# If not set custom url: if user pages, then use "/"; if project page, use "/project-name" (without trailing slash).
baseurl: /
url: http://www.jimgray.tk
paginate: 5

# Site info
title: ZNHOO
tagline: 'Whatever you are, be a good one!'
description: 'I am ZNHOO. Make yourself at home. Contact me at <a href="https://twitter.com/znhoo" target="_blank">@znhoo</a>.'

# About/contact
author:
  name: ZNHOO
  url: https://www.jimgray.tk
  email: znhoo@noreply.com

# Custom vars
version: 1.0.0


