# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ZNHOO
tagline:             'Whatever you are, be a good one!'
description:         'I am ZNHOO. Make yourself at home. Contact me at <a href="https://twitter.com/znhoo" target="_blank">@znhoo</a>.'

# if user pages, then use "/"; if project page, use "/project-name". Note the slash issue. If you include trailing slash, then should omit duplicated slash when accessing files.
baseurl:             /
paginate:            5

# About/contact
author:
  name:              ZNHOO
  url:               https://twitter.com/znhoo
  email:             bob@noreply.com

# Custom vars

version:             1.0.0

# deprecated vars

#github:
#  repo:  https://github.com/outsinre/outsinre.github.com

#url		     http://www.fangxiang.tk
