# Dependencies
markdown:	redcarpet
highlighter:	pygments

# Permalinks
permalink:	pretty

# Use of `relative_permalinks` ensures post links from the index work properly.
# `relative_permalinks` deprecated now. Remove it.
#
#relative_permalinks:	true

# encoding of filenames
encoding:	utf-8

# Setup
title:		ZNHOO
tagline:	'Whatever you are, be a good one!'
description:	'I am ZNHOO. Make yourself at home. Contact me at <a href="https://twitter.com/znhoo" target="_blank">@znhoo</a>.'

# If not set custom url: if user pages, then use "/"; if project page, use "/project-name" (without trailing slash).
baseurl:	/
paginate:	5

# About/contact
author:
  name:		ZNHOO
  url:		https://twitter.com/znhoo
  email:	znhoo@noreply.com

# Custom vars
version:	1.0.0
url:		http://jimgray.tk

