# https://help.github.com/articles/configuring-jekyll/

markdown: kramdown

# https://stackoverflow.com/a/25597026
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

encoding: utf-8

url: http://www.fxhu.tk
baseurl: ''

permalink: pretty

paginate: 5

title: ZNHOO
tagline: 'Whatever you are, be a good one!'
description: 'Make yourself at home. Contact me at <a href="mailto:{{ site.author.email }}">(youwu at inventati dot org)</a>.'

author:
  name: ZNHOO
  email: youwu@inventati.org

# Custom vars
version: 1.0.0
