# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ZNHOO
tagline:             'Whatever you are, be a good one!'
description:         'I am ZNHOO. Make yourself at home. Contact me at twitter <a href="https://twitter.com/znhoo" target="_blank">@znhoo</a>.'
url:                 http://0110.ml
baseurl:             /
paginate:            5

# About/contact
author:
  name:              ZNHOO
  url:               https://twitter.com/znhoo
  email:             bob@gmail.com

# Custom vars

github:
  repo:		     github.com/outsinre/outsinre.github.com

version:             1.0.0